// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DHni8cyrdwhrJkq9GAyD0jX97vhf2QE',
    appId: '1:966117448786:web:00e88214db072e33b0938b',
    messagingSenderId: '966117448786',
    projectId: 'evoltsoft-faefb',
    authDomain: 'evoltsoft-faefb.firebaseapp.com',
    storageBucket: 'evoltsoft-faefb.appspot.com',
    measurementId: 'G-R863R3L1WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KcBe_CoJggHBWFlg5n15kGJvo1dEfIA',
    appId: '1:966117448786:android:dfb30a2dd1338b48b0938b',
    messagingSenderId: '966117448786',
    projectId: 'evoltsoft-faefb',
    storageBucket: 'evoltsoft-faefb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDei2NKT2s8zj2B1zeycxsz4xUSlHzJbK4',
    appId: '1:966117448786:ios:a67c734273dda94ab0938b',
    messagingSenderId: '966117448786',
    projectId: 'evoltsoft-faefb',
    storageBucket: 'evoltsoft-faefb.appspot.com',
    iosBundleId: 'com.example.evoltsoft2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDei2NKT2s8zj2B1zeycxsz4xUSlHzJbK4',
    appId: '1:966117448786:ios:a67c734273dda94ab0938b',
    messagingSenderId: '966117448786',
    projectId: 'evoltsoft-faefb',
    storageBucket: 'evoltsoft-faefb.appspot.com',
    iosBundleId: 'com.example.evoltsoft2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DHni8cyrdwhrJkq9GAyD0jX97vhf2QE',
    appId: '1:966117448786:web:bb61ab43f08f52aab0938b',
    messagingSenderId: '966117448786',
    projectId: 'evoltsoft-faefb',
    authDomain: 'evoltsoft-faefb.firebaseapp.com',
    storageBucket: 'evoltsoft-faefb.appspot.com',
    measurementId: 'G-R0W7LKCBTH',
  );

}